import Header from "@/components/Header/Header";
import "@/styles/globals.css";
import ConstructionContextProvider from "@/context/constructionContext";
import Footer from "@/components/Footer/Footer";

export const metadata = {
	title: {
		default: "Create Next App",
		template: `Create Next App | %s`,
	},
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="fa">
			<body className="bg-gray-50 relative">
				<ConstructionContextProvider>
					<Header />
					{children}
					<Footer />
				</ConstructionContextProvider>
			</body>
		</html>
	);
}
